# Generated by Django 3.2.6 on 2021-10-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_auto_20211003_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='identity',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='hero',
            name='strength',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='hero',
            name='weakness',
            field=models.TextField(default='', max_length=300),
        ),
    ]
