# Generated by Django 3.2.6 on 2021-11-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0005_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('story', models.TextField(max_length=400)),
            ],
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
