# Generated by Django 3.2.6 on 2021-10-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_hero_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='strength',
            field=models.TextField(default='hi', max_length=300),
        ),
        migrations.AddField(
            model_name='hero',
            name='weakness',
            field=models.TextField(default='hi', max_length=300),
        ),
        migrations.AlterField(
            model_name='hero',
            name='identity',
            field=models.TextField(default='hi', max_length=300),
        ),
    ]
