# Generated by Django 3.2.6 on 2021-11-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0004_auto_20211006_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
